version: '3'
services:
  jenkins_master:
    restart: always
    build: 
      context: .
      args:
        dockergroupid: ${DOCKER_GROUP_ID}
    image: gtunon/docker_master:beta
    container_name: jenkins_master
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/dockerImages:/home/ubuntu/dockerImages
      - built_jars:/home/ubuntu/shared/jars
    ports:
      - "8081:8080"
      - "50000:50000"

volumes:
  jenkins_home: {}
  built_jars: {}

